common:
  img_topic: "/camera/color/image_raw"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 0
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [  0.041, 0.02329, -0.028 ]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]


time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.1


preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6
  blind: 0.5

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.2 # 0.2
  gyr_cov: 0.005 # 0.5
  b_acc_cov: 0.00005 # 0.1
  b_gyr_cov: 0.00005 # 0.1

lio:
  max_iterations: 8
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.01 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: false      # LRU 替代 sliding
  max_voxel_count: 10000     # 最大体素数量
  max_memory_mb: 800         # 最大内存 MB
uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
